Final Production line control/color_station_control/color_APP/urls.py
from django.urls import path
from color_APP.views import *

#All URLs we can see in urlpatterns 
urlpatterns = [
    path('',Stations.as_view(),name='stations'),
    path('station/<int:pk>/',StationDetail.as_view(),name="stationdetail"),
    path('faults/',Faults.as_view(),name='faults'),
    path('faults/<int:pk>/',FaultDetail.as_view(),name='faultdetail'),
    path('newstation/',StationCreate.as_view(),name='stationcreate'),
    path('newfault/',FaultCreate.as_view(),name='faultcreate'),
    path('newreport/',ReportCreate.as_view(),name='reportcreate'),
    path('editstation/<int:pk>/',StationUpdate.as_view(),name='stationupdate'),
    path('editfault/<int:pk>/',FaultUpdate.as_view(),name='faultupdate'),
    path('deletestation/<int:pk>/',StationDelete.as_view(),name='stationdelete'),
    path('deleteFault/<int:pk>/',FaultDelete.as_view(),name='faultdelete'),
    path('editreport/<int:pk>/',ReportUpdate.as_view(),name='reportupdate'),
    path('deletreport/<int:pk>/',ReportDelete.as_view(),name='reportdelete'),
    path('pieces/',Pieces.as_view(),name='pieces'),
    path('newpiece/',PieceCreate.as_view(),name='piececreate'),
    path('editpiece/<int:pk>/',PieceUpdate.as_view(),name='pieceupdate'),
    path('deletepiece/<int:pk>/',PieceDelete.as_view(),name='piecedelete'),
    path('newequip/',EquipCreate.as_view(),name='equipcreate'),
    path('equipdetail/<int:pk>/',EquipDetail.as_view(),name='equipdetail'),
    path('equipstation/<int:pk>/',EquipStation.as_view(),name='equipstation'),
    path('deleteequip/<int:pk>/',EquipDelete.as_view(),name='equipdelete'),
    path('editequip/<int:pk>/',EquipUpdate.as_view(),name='equipupdate'),
    path('stationreport/',StationReport.as_view(),name='stationreport'),
    path('stationjson/',stationsJson,name='stationjson'),


    
] 

Final Production line control/color_station_control/color_station_control/urls.py
from django.contrib import admin
from django.urls import path, include
from color_station_control import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('color_APP.models')),
]

if not settings.DEBUG:
    pass
else:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Final Production line control/color_station_control/color_APP/models.py
import datetime

from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.urls import reverse
from django_jalali.db import models as jmodels


class Station(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    @staticmethod
    def get_absolute_url():
        return reverse("stations")


class Fault(models.Model):
    name = models.CharField(max_length=100)
    file = models.FileField(null=True, blank=True)

    def __str__(self):
        return self.name

    @staticmethod
    def get_absolute_url():
        return reverse("faults")


class Report(models.Model):
    fault = models.ForeignKey('Fault', blank=True, on_delete=models.SET_NULL, null=True)
    station = models.ForeignKey('Station', on_delete=models.SET_NULL, null=True, blank=False)
    description = models.TextField(null=True, blank=True)
    shift = models.CharField(max_length=1, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], null=True, blank=True)
    reporter = models.CharField(max_length=100, null=True, blank=True)
    expert = models.CharField(max_length=100, null=True, blank=True)
    opinion = models.TextField(null=True, blank=True)
    piece = models.ManyToManyField('Piece', blank=True)
    date = jmodels.jDateField()
    startTime = models.TimeField()
    endTime = models.TimeField()
    stopTime = models.TimeField(blank=True)
    samp = models.URLField(null=True, blank=True)
    cReport = models.TextField(null=True, blank=True)
    equip = models.ForeignKey('Equip', on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return str(self.fault) + " " + str(self.station)


class Equip(models.Model):
    name = models.CharField(max_length=100)
    station = models.ForeignKey('Station', on_delete=models.CASCADE)

    def __str__(self):
        return self.name


@receiver(pre_save, sender=Report)
def calcStopTime(sender, instance, **kwargs):
    end = str(instance.endTime).split(':')
    start = str(instance.startTime).split(':')
    instance.stopTime = str(
        datetime.timedelta(hours=int(end[0]), minutes=int(end[1]), seconds=int(end[2])) - datetime.timedelta(
            hours=int(start[0]), minutes=int(start[1]), seconds=int(start[2])))


class Piece(models.Model):
    name = models.CharField(max_length=100)
    ikco_id = models.CharField(max_length=100)
    technical_id = models.CharField(max_length=100)

    def __str__(self):
        return self.name

Final Production line control/color_station_control/color_APP/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from color_APP.models import *
from django.urls import reverse_lazy
import django.http
import json as JSON


class Stations(ListView):
    model = Station
    template_name = "station.html"


class Faults(ListView):
    model = Fault
    template_name = "faults.html"


class StationDetail(DetailView):
    model = Station
    template_name = 'stationdetail.html'


class FaultDetail(DetailView):
    model = Fault
    template_name = "faultdetail.html"


class StationCreate(CreateView):
    model = Station
    template_name = "stationcreate.html"
    fields = '__all__'


class ReportCreate(CreateView):
    model = Report
    fields = "__all__"
    template_name = 'reportcreate.html'

    # success_url='/'     
    def get_success_url(self):
        return reverse_lazy('stationdetail', args=(int(self.request.POST.get('station')),))


class FaultCreate(CreateView):
    model = Fault
    template_name = "faultcreate.html"
    fields = '__all__'


class StationUpdate(UpdateView):
    model = Station
    template_name = "stationupdate.html"
    fields = '__all__'


class FaultUpdate(UpdateView):
    model = Fault
    template_name = "faultupdate.html"
    fields = '__all__'


class ReportUpdate(UpdateView):
    model = Report
    template_name = 'reportupdate.html'
    fields = '__all__'

    def get_success_url(self):
        return reverse_lazy('stationdetail', args=(self.object.station.id,))


class StationDelete(DeleteView):
    model = Station
    template_name = "stationdelete.html"
    success_url = reverse_lazy('stations')


class FaultDelete(DeleteView):
    model = Fault
    template_name = "faultdelete.html"
    success_url = reverse_lazy('faults')


class ReportDelete(DeleteView):
    model = Report
    template_name = 'reportdelete.html'

    def get_success_url(self):
        return reverse_lazy('stationdetail', args=(self.object.station.id,))


class Pieces(ListView):
    model = Piece
    template_name = 'pieces.html'


class PieceCreate(CreateView):
    model = Piece
    template_name = 'piececreate.html'
    fields = '__all__'
    success_url = reverse_lazy('pieces')


class PieceUpdate(UpdateView):
    model = Piece
    template_name = 'pieceupdate.html'
    fields = '__all__'
    success_url = reverse_lazy('pieces')


class PieceDelete(DeleteView):
    model = Piece
    template_name = 'piecedelete.html'
    success_url = reverse_lazy('pieces')


class EquipCreate(CreateView):
    model = Equip
    template_name = 'equipcreate.html'
    fields = '__all__'

    def get_success_url(self):
        return reverse_lazy('stationdetail', args=(self.object.station.id,))


class EquipStation(DetailView):
    template_name = 'equipstation.html'
    model = Station


class StationReport(TemplateView):
    template_name = 'stationreport.html'


def stationsJson(request):
    len([1, 5])
    json = {}
    stations = Station.objects.all()
    for station in stations:
        json[station.name] = {}
        json[station.name]['equips'] = {}
        json[station.name]['reports'] = len(list(station.report_set.all()))
        for equip in station.equip_set.all():
            json[station.name]['equips'][equip.name] = len(list(equip.report_set.all()))
    return django.http.HttpResponse(JSON.dumps(json), content_type="application/json")


class EquipDetail(DetailView):
    model = Equip
    template_name = 'equipdetail.html'


class EquipDelete(DeleteView):
    model = Equip
    template_name = 'equipdelete.html'

    def get_success_url(self):
        return reverse_lazy('equipstation', args=(self.object.station.id,))


class EquipUpdate(UpdateView):
    model = Equip
    fields = '__all__'
    template_name = "equipupdate.html"

    def get_success_url(self):
        return reverse_lazy('equipstation', args=(self.object.station.id,))

Final Production line control/color_station_control/color_APP/templates/base.html
{% load static %}
<!DOCTYPE html>
<html dir='rtl' lang="fa">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel='stylesheet' href={% static 'styles/base.css' %}>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    {% comment %} <link href="https://cdn.rawgit.com/harvesthq/chosen/gh-pages/chosen.min.css" rel="stylesheet"/> {% endcomment %}
    <link href="{% static 'styles/chosen.min.css' %}" rel="stylesheet"/>
    <link rel="stylesheet" href="{% static 'styles/persian.datepicker.css'%}"/>
    <link rel="stylesheet" href="{% static 'styles/chart.css' %}">
    <title> {% block title %}{% endblock title %} </title>
</head>
<body>
    
    <nav>
        <div class="topnav">
            <a href={% url 'stations' %}>ایستگاه ها</a>
            <a href=" {%url 'stationcreate' %} ">ایستگاه جدید</a>
            <a href="{% url 'faults' %}">خطاها</a>
            <a href=" {% url 'faultcreate' %} ">خطا جدید</a> 
            <a href=" {% url 'reportcreate' %} ">گزارش جدید</a>
            <a href="{%url 'pieces'%}">قطعات</a>
            <a href={% url 'stationreport' %} >نمودار درصد خرابی</a>   
        </div>
           
    </nav>

    <div class='main'>

        {% block content %}{% endblock content %}
    </div>
    </body>
    {% comment %} <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script> {% endcomment %}
    {% comment %} <script src="https://cdn.rawgit.com/harvesthq/chosen/gh-pages/chosen.jquery.min.js"></script> {% endcomment %}
    <script type="text/javascript" src="{% static 'scripts/canvasjs.min.js' %}"></script>
    <script src="{% static 'scripts/jquery.min.js' %}"></script>
    <script src="{% static 'scripts/chosen.jquery.min.js' %}"></script>
    <script src="{% static 'scripts/persian.date.js'%}"></script>
    <script src="{% static 'scripts/persian.datepicker.js'%}"></script>



    <script src="{%static 'scripts/base.js'%}"></script>
</html>

Final Production line control/color_station_control/color_APP/templates/equipdelete.html
{% extends 'base.html' %}

{% block content %}
<form method='post'>
    {% csrf_token %}
    <p>آیا از درخواست خود اطمینان دارید؟</p>
    <button type='submit' class='button primary delete'>حذف</button>
    <a class='button primary cancel' href="{% url 'equipstation' equip.station.id %}">لغو<a>

{% endblock content %}

Final Production line control/color_station_control/color_APP/templates/equipdetail.html
{% extends 'base.html' %}
{% block content %}








<div class="table-container">
    <table class="styled-table">
        <thead>
            <tr class='under'>
                <th></th><th></th><th></th><th></th><th></th><th></th><th></th><th></th><th></th><th></th><th></th><th></th>
                <th></th><th></th>
                
                <th>{{equip.station.name}} {{equip.name}} </th>
                <th>ایستگاه  </th>
            </tr>
        </thead>
        <thead>
            <tr>
                <th>حذف گزارش</th>
                <th>ویرایش گزارش</th>
                <th>سمپ</th>
                <th>گزارش تکمیلی</th>
                <th>قطعه تعویض شده</th>
                <th>نظر کارشناس</th>
                <th>کارشناس مربوطه</th>
                <th>گزارش کننده</th>
                <th>زمان توقف</th>
                <th>ساعت پایان</th>
                <th>ساعت شروع</th>
                <th>شیفت</th>
                <th>تاریخ</th>
                {% comment %} <th>فایل مربوطه</th> {% endcomment %}
                <th>شرح مختصر</th>
                <th>تجهیز</th>
                <th>نام خطا</th>
    
    
            </tr>
        </thead>
        <tbody>
            {% for report in equip.report_set.all %}

            <tr {% if report.id|divisibleby:2 %} class="active-row"{% endif %} >
                    
                <th><a href={% url 'reportdelete' report.id %} class="button condensed delete">حذف</a></th>        
                <th><a href={% url 'reportupdate' report.id %} class="button condensed edit", >ویرایش</a></th>
        
                
                <th>{{report.samp}}</th>
                <th> {{report.cReport}} </th>
                    <th>{% if report.piece.all %}{{report.piece.all}}{%else%}بدون تعویض {% endif %}</th>
                    <th>{{report.opinion}}</th>
                    <th>{{report.expert}}</th>
                    <th>{{report.reporter}}</th>
                    <th>{{report.stopTime|time:"H:i"}}</th>
                    <th>{{report.endTime|time:"H:i"}}</th>
                    <th> {{report.startTime|time:"H:i"}} </th>
                    <th>{{report.shift}}</th>
                    <th>{{report.date}}</th>
                    {% comment %} <th><a class='button condensed cancel' href={% if report.fault.file %}" {{report.fault.file.url}} "{% endif %}>جزئیات</a></th> {% endcomment %}
                    <th> {{report.description}} </th>
                    <th><a >{{report.equip}}</a></th>
                    <th><a href={% if report.fault.id %}"{% url 'faultdetail' report.fault.id %}"{% endif %}> {{report.fault.name}} </a></th>
            {% endfor %}
            
        </tbody>
    </table>
    
    </div>
    
{% endblock content %}

Final Production line control/color_station_control/color_APP/templates/equipstation.html
{% extends 'base.html' %}

{% block content %}
<div class="table-container">
    <table class="styled-table">
        <thead>
            <tr class='under'>
                <th></th>
                <th>{{station.name}}</th>
                <th>ایستگاه  </th>
            </tr>
        </thead>
        <thead>
            <tr>
                <th></th><th></th>
                <th>نام تجهیز</th>
    
    
            </tr>
        </thead>
        <tbody>
            {% for equip in station.equip_set.all %}
            <tr {% if equip.id|divisibleby:2 %} class="active-row"{% endif %} >
                    
                <th><a href={% url 'equipdelete' equip.id %} class="button condensed delete">حذف</a></th>        
                <th><a href={% url 'equipupdate' equip.id %} class="button condensed edit", >ویرایش</a></th>
                <th><a href='{% url 'equipdetail' equip.id %}'> {{equip.name}}</a> </th>        
        
        
            </tr>
            {% endfor %}
        </tbody>
    </table>
    
    </div>
    

{% endblock content %}

Final Production line control/color_station_control/color_APP/templates/equipupdate.html
{% extends 'base.html' %}
{% block content %}

<form method="post">
    {% csrf_token %}
    <label>نام تجهیز: </label>{{form.name}}<br>
    <label>ایستگاه: </label> {{form.station}} <br>
    <button type='submit' class="button primary save"> ذخیره</button>
</form>
{% endblock content %}

Final Production line control/color_station_control/color_APP/templates/faultdelete.html
{% extends 'base.html' %}
{% block title %}Delete Fault{% endblock title %}
{% block content %}
<p>
    <form method='post'>
        از درخواست خود اطمینان دارید؟
        {% csrf_token %}
        <button type="submit" class='button condensed delete'>حذف</button>
        <a href="{% url 'faultdetail' fault.id %}" class='button condensed cancel'>لغو</a>
    </form>
</p>
{% endblock content %}

Final Production line control/color_station_control/color_APP/templates/faultdetail.html
{% extends 'base.html' %}
{% block title %} {{fault.name}} {% endblock title %}
{% block content %}



<table class="styled-table">
    
    <thead>
        <tr>
            <th> فایل مربوطه</th>
            <th>نام خطا</th>
        </tr>
    </thead>
    <tbody>
        
        <tr>
            {% if fault.file %}
            <td><a href={{fault.file.url}}>{{fault.file}}</a></td>
            {% else %}
            <td></td>
            {% endif %}
            <td>{{fault.name}} </td>
            
        
    </tbody>
</table>

<p>
    
    <a class="button primary edit", href="{% url 'faultupdate' fault.id %}">ویرایش</a>
    <a href="{% url 'faultdelete' fault.id %}" class="button primary delete">حذف</a>
</p>

{% endblock content %}

Final Production line control/color_station_control/color_APP/templates/faultupdate.html
{% extends 'base.html' %}
{% block title %}Edit Fault{% endblock title %}
{% block content %}
<div>

    <form method='post' enctype='multipart/form-data'>
        {% csrf_token %}
        <p><label>نام خطا:</label> {{form.name}} </p>
        <p><label>فایل مربوطه:</label>{{form.file}}</p>
        <button class="button primary save" type="submit">ذخیره</button>
    </form>


</div>



{% endblock content %}

Final Production line control/color_station_control/color_APP/templates/pieces.html
{% extends 'base.html' %}
{% block content %}


<table class="styled-table">
    <thead>
        <tr>
            <th></th><th></th>
            <th>کد ایرانخودرویی</th>
            <th>کد فنی</th>
            <th>نام قطعه</th>
        </tr>
    </thead>
    <tbody>
        
        {% for piece in piece_list %}
            <tr {% if piece.id|divisibleby:2 %} class="active-row"{% endif %}>
                    
                <th><a href={% url 'piecedelete' piece.id %} class="button condensed delete">حذف</a></th>        
                <th><a href={% url 'pieceupdate' piece.id %} class="button condensed edit", >ویرایش</a></th>
            
                <td>{{piece.ikco_id}}</td>
                <td> {{piece.technical_id}} </td>
                <td>{{piece.name}}</td>
            </tr>
        {% endfor %}
        
    </tbody>
</table>

<a class='button primary new' href=" {% url 'piececreate' %} " >افزودن قطعه جدید</a>




{% endblock content %}

Final Production line control/color_station_control/color_APP/templates/pieceupdate.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <label>نام قطعه:</label>{{form.name}}<br><br>
    <label>کد ایرانخودرویی:</label>{{form.ikco_id}}<br><br>
    <label>کد تکنیکال:</label>{{form.technical_id}}<br><br>
    <button class="button primary save" type="submit">ذخیره</button>


</form>

{% endblock content %}

Final Production line control/color_station_control/color_APP/templates/reportcreate.html
{% extends 'base.html' %}
{% block content %}

  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" />
  <div class="container">
    <form method='post'>
        {% csrf_token %}
    </div>
      <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 " id="upload_basic_info">
        <div class="form-group">
            <label>خطا:</label>{{form.fault}}<br>
          <div class="help-block with-errors"></div>
        </div>
  
        <div class="form-group">
            <label>ایستگاه:</label>{{form.station}}<br>
          <div class="help-block with-errors"></div>
        </div>
  
        <div class="form-group">
            <label>توضیحات:</label>{{form.description}}<br>
          <div class="help-block with-errors"></div>
        </div>
        <div class="form-group">
            <label>شیفت:</label>{{form.shift}}<br>
          <div class="help-block with-errors"></div>
        </div>
      </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
            <div class="form-group">
                <label>گزارش دهنده:</label>{{form.reporter}}<br>
            </div>
          </div>
      <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
        <div class="form-group">
            <label>کارشناس مربوطه:</label>{{form.expert}}<br>
        </div>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
        <div class="form-group">
            <label>نظر کارشناس:</label>{{form.opinion}}<br>
        </div>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
        <div class="form-group">
            <label>قطعه های تعویض شده:</label>{{form.piece}}<br>
        </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
        <div class="form-group">
            <label>تاریخ:</label>{{form.date}} <br>
        </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
        <div class="form-group">
            <label>ساعت پایان:</label>{{form.endTime}}<br>
        </div>
    </div>
    
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
        <div class="form-group">
            <label>ساعت شروع:</label>{{form.startTime}}<br>
        </div>
    </div>
    
    <div class="col-lg-7 col-md-7 col-sm-7 col-xs-7">
        <div class="form-group">
            <br><br><button class="button primary save" type="submit">ذخیره</button></div>
    </div>
</div>
</div>

{% endblock content %}

Final Production line control/color_station_control/color_APP/templates/reportdelete.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <p>آیا از درخواست خود اطمینان دارید؟</p>
    <p><button type="submit" class="button primary delete"> حذف</button><a href=" {%url 'stationdetail' report.station.id%} " class="button primary cancel">لغو</a></p>
</form>



{% endblock content %}

Final Production line control/color_station_control/color_APP/templates/station.html
{% extends 'base.html' %}
{% block title %}Stations{% endblock title %}

{% block content %}
  
<table class="styled-table">
    <thead>
        <tr>
            <th></th>
            <th>نام ایستگاه</th>
        </tr>
    </thead>
    <tbody>
        
        {% for station in station_list %}
            <tr {% if station.id|divisibleby:2 %} class="active-row"{% endif %}>
                <td><a class='button condensed cancel' href=" {% url 'stationdetail' station.id %} ">جزئیات</a></td>
                <td>{{station.name}}</td>
            </tr>
        {% endfor %}
        
    </tbody>
</table>
        
{% endblock content %}
    

Final Production line control/color_station_control/color_APP/templates/stationcreate.html
{% extends 'base.html' %}
{% block title %}New Station{% endblock title %}
{% block content %}


    <form method="post">
        {% csrf_token %}
        <p><label>نام ایستگاه:</label> {{form.name}} </p>
        
        <button class="button primary save" type="submit">ذخیره</button>
    </form>

{% endblock content %}